import { QuestionTree } from "@/types/esg-form";

export const gt: QuestionTree = [
  {
    id: "1",
    value:
      "Votre entreprise respecte t-elle la règlementation en matière de droit du travail, du code de l'environnement, du droit des affaires ?",
    ids_secteurs: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 17, 18, 19, 22, 23, 24, 25,
      26, 28, 29,
    ],
    id_action: null,
    information:
      "Cette question évalue l'engagement de votre entreprise à respecter les lois et règlements qui régissent ses activités. Le respect du droit du travail assure une protection adéquate des droits des employés, favorisant ainsi un environnement de travail éthique et juste. La conformité au code de l'environnement démontre l'engagement de votre entreprise envers la durabilité et la préservation des ressources naturelles. Enfin, se conformer au droit des affaires renforce la transparence et l'éthique dans les opérations commerciales, ce qui est essentiel pour instaurer la confiance avec les parties prenantes.\n\nRespecter ces réglementations est une obligation légale pour toutes les entreprises, et le non-respect peut entraîner des sanctions juridiques, des amendes et des dommages à la réputation de l'entreprise.\n\n👉 Exemple : Établir des politiques internes claires et des formations régulières pour sensibiliser les employés aux lois pertinentes et garantir que les pratiques de l'entreprise sont conformes aux réglementations en vigueur.",
    children: [
      {
        id: "2",
        value: "Oui",
        id_action: null,
        done: true,
        information: null,
        children: [
          {
            id: "3",
            value:
              "Comment votre entreprise respecte t-elle la règlementation en matière de droit du travail, du code de l'environnement, du droit des affaires ?",
            id_action: null,
            information: null,
            children: [
              {
                id: "4",
                value: "Evaluation de la conformité règlementaire",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "5",
                value: "Certifications ISO, labels",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "6",
                value: "Audits externes, inspections, contrôles",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "7",
                value:
                  "Politiques et procédures internes, manuels internes, guides de conformité",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "8",
                value:
                  "Evaluation des risques, plans d'action d'atténuation des risques",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
            ],
            type: "question",
            inputType: "multiple",
          },
        ],
        type: "reponse",
      },
      {
        id: "9",
        value: "Non",
        id_action: 401,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
      {
        id: "10",
        value: "Ne sait pas",
        id_action: 402,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "11",
    value: "Votre démarche RSE est-elle formalisée ?",
    ids_secteurs: [
      1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23,
      24, 25, 26, 27, 28, 29,
    ],
    id_action: null,
    information: null,
    children: [
      {
        id: "12",
        value: "Oui",
        id_action: 403,
        done: true,
        information: null,
        children: [
          {
            id: "13",
            value: "Comment formalisez-vous votre démarche RSE ?",
            id_action: null,
            information:
              "Cette question permet d'évaluer comment votre entreprise structure et communique ses engagements en matière de responsabilité sociétale. Une démarche RSE formalisée démontre un engagement sincère envers les enjeux sociaux, environnementaux et économiques. Les différentes options présentées permettent d'identifier si votre entreprise utilise des outils tels que des rapports annuels, des chartes d'engagement, des indicateurs de performance, ou des objectifs spécifiques pour guider ses actions. Une démarche clairement articulée renforce la transparence et la confiance des parties prenantes.\n\n👉 Exemple : Publier un rapport annuel sur le Développement Durable, qui détaille les actions entreprises et les résultats obtenus, contribue à une meilleure communication et responsabilisation des actions RSE de l'entreprise.",
            children: [
              {
                id: "14",
                value:
                  "Un rapport est publié chaque année (Développement Durable, RSE, etc.)",
                id_action: null,
                done: false,
                information:
                  "Ce rapport permet de communiquer de manière transparente les actions entreprises, les résultats obtenus et les objectifs futurs en matière de RSE, renforçant ainsi la responsabilité et la confiance auprès des parties prenantes.",
                children: [],
                type: "reponse",
              },
              {
                id: "15",
                value:
                  "Une charte d'engagement, une charte de Développement Durable interne guide vos actions",
                id_action: null,
                done: false,
                information:
                  "Cette charte formalise les valeurs et les engagements de l'entreprise en matière de développement durable, servant de guide pour les employés et affirmant la volonté de l'entreprise de respecter des pratiques responsables.",
                children: [],
                type: "reponse",
              },
              {
                id: "16",
                value: "Vos indicateurs clés sont analysés chaque année",
                id_action: null,
                done: false,
                information:
                  "L'utilisation d'indicateurs clés permet de mesurer les progrès réalisés dans les actions RSE et d'évaluer l'impact des initiatives mises en œuvre, facilitant ainsi l'ajustement des stratégies.",
                children: [],
                type: "reponse",
              },
              {
                id: "17",
                value:
                  "Des objectifs sont déclinés dans vos plans opérationnels",
                id_action: null,
                done: false,
                information:
                  "L'intégration d'objectifs RSE spécifiques dans les plans opérationnels assure que la responsabilité sociétale est intégrée dans la stratégie globale de l'entreprise, rendant ces objectifs mesurables et réalisables.",
                children: [],
                type: "reponse",
              },
              {
                id: "18",
                value: "Autre(s)",
                id_action: null,
                done: false,
                information: null,
                children: [
                  {
                    id: "19",
                    value: "Veuillez préciser :",
                    id_action: null,
                    information: null,
                    children: [],
                    type: "question",
                    inputType: "text",
                    id_kpis: [],
                  },
                ],
                type: "reponse",
              },
            ],
            type: "question",
            inputType: "multiple",
          },
        ],
        type: "reponse",
      },
      {
        id: "21",
        value: "Non",
        id_action: 403,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "22",
    value:
      "Votre organisation intègre-t-elle la réponse aux Objectifs de Développement Durable dans sa stratégie ?",
    ids_secteurs: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 17, 18, 19, 22, 23, 24, 25,
      26, 28, 29,
    ],
    id_action: null,
    information:
      "Cette question vise à évaluer si votre organisation aligne ses activités et sa stratégie sur les Objectifs de Développement Durable (ODD) des Nations Unies, qui visent à répondre aux défis mondiaux tels que la pauvreté, les inégalités et la protection de l'environnement. L'intégration des ODD dans la stratégie de l'organisation démontre un engagement à contribuer à un développement durable et à une société plus équitable, renforçant ainsi sa réputation et sa relation avec les parties prenantes.",
    children: [
      {
        id: "23",
        value: "Oui",
        id_action: 404,
        done: true,
        information: null,
        children: [
          {
            id: "24",
            value:
              "Comment votre organisation intègre-t-elle la réponse aux Objectifs de Développement Durable dans sa stratégie ?",
            id_action: null,
            information: null,
            children: [
              {
                id: "25",
                value:
                  "Le but principal de notre entreprise est de répondre à l'un des 17 ODD, avant même la performance financière",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "26",
                value:
                  "Dans l'échelle des priorités, la performance financière et la réponse à l'un des ODD sont au même niveau",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "27",
                value:
                  "La performance financière de notre entreprise est la priorité, mais notre entreprise contribue activement à résoudre l'un des ODD grâce à son cœur d'activité",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "28",
                value:
                  "La performance financière est la priorité, et notre entreprise répond à l'un des ODD en marge de son activité",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
            ],
            type: "question",
            inputType: "single",
          },
        ],
        type: "reponse",
      },
      {
        id: "29",
        value: "Non",
        id_action: 404,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "30",
    value: "Avez-vous cartographié vos parties prenantes ?",
    ids_secteurs: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 17, 18, 19, 22, 23, 24, 25,
      26, 28, 29,
    ],
    id_action: null,
    information:
      "Cette question permet d'évaluer si votre organisation a identifié et analysé les différentes parties prenantes qui influencent ou sont influencées par ses activités. La cartographie des parties prenantes est essentielle pour comprendre les attentes, les intérêts et les impacts potentiels de l'organisation sur ces groupes. En ayant une vue d'ensemble des parties prenantes, votre organisation peut mieux orienter sa stratégie RSE et renforcer ses relations avec les acteurs clés, ce qui favorise une gouvernance plus responsable et inclusive.",
    children: [
      {
        id: "31",
        value: "Oui",
        id_action: 405,
        done: true,
        information: null,
        children: [],
        type: "reponse",
      },
      {
        id: "32",
        value: "Non",
        id_action: 405,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "33",
    value: "Recueillez-vous les attentes de vos parties prenantes ?",
    ids_secteurs: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 17, 18, 19, 22, 23, 24, 25,
      26, 28, 29,
    ],
    id_action: null,
    information: null,
    children: [
      {
        id: "34",
        value: "Oui",
        id_action: 406,
        done: true,
        information: null,
        children: [],
        type: "reponse",
      },
      {
        id: "35",
        value: "Non",
        id_action: 406,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "36",
    value:
      "Votre entreprise garantit-elle la transparence de ses opérations, de ses pratiques commerciales et de ses informations financières afin de communiquer avec ses parties prenantes ?",
    ids_secteurs: [
      1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23,
      24, 25, 26, 27, 28, 29,
    ],
    id_action: null,
    information:
      "Cette question évalue si votre organisation met en place des mécanismes pour identifier et comprendre les attentes, besoins et préoccupations de ses parties prenantes. Recueillir ces informations est essentiel pour adapter la stratégie RSE de l'organisation et renforcer les relations avec les parties prenantes. Une écoute active permet de mieux répondre aux enjeux sociaux et environnementaux, de minimiser les risques et de favoriser une gouvernance inclusive et transparente.",
    children: [
      {
        id: "37",
        value: "Oui",
        id_action: 407,
        done: true,
        information: null,
        children: [
          {
            id: "38",
            value:
              "Comment votre entreprise garantit-elle la transparence de ses opérations, pratiques commerciales et informations financières envers ses parties prenantes ?",
            id_action: null,
            information:
              "Cette question évalue les mécanismes et les pratiques que votre entreprise met en place pour garantir la transparence dans ses opérations et ses communications. La transparence est un pilier fondamental de la gouvernance responsable, car elle favorise la confiance des parties prenantes, réduit les risques de malentendus et d'incompréhensions et démontre l'engagement de l'entreprise envers l'éthique et la responsabilité. Une communication claire et ouverte permet également aux parties prenantes de prendre des décisions éclairées basées sur des informations fiables.",
            children: [
              {
                id: "39",
                value:
                  "En publiant régulièrement des rapports de durabilité détaillés, couvrant les pratiques environnementales, sociales et de gouvernance de l'entreprise",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "40",
                value:
                  "En fournissant un accès facile aux informations financières clés telles que les états financiers, les bilans et des rapports d'audit",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "41",
                value:
                  "En divulguant vos politiques et procédures internes, y compris vos codes de conduite et vos politiques de gestion des risques.",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "42",
                value:
                  "En rendant publics les objectifs et progrès en matière de durabilité de l'entreprise, notamment les efforts de réduction de l'empreinte carbone",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "43",
                value:
                  "En encourageant activement les retours d'information et les questions des parties prenantes de l'entreprise pour garantir une communication ouverte",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "44",
                value:
                  "En organisant régulièrement des réunions d'information ouvertes avec les clients, fournisseurs et autres parties prenantes de l'entreprise pour discuter d'activités de l'entreprise",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "45",
                value:
                  "En garantissant la conformité totale avec les exigences légales en matière de divulgation d'informations",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "46",
                value: "Autre(s)",
                id_action: null,
                done: false,
                information: null,
                children: [
                  {
                    id: "47",
                    value: "Veuilez préciser :",
                    id_action: null,
                    information: null,
                    children: [],
                    type: "question",
                    inputType: "text",
                    id_kpis: [],
                  },
                ],
                type: "reponse",
              },
            ],
            type: "question",
            inputType: "multiple",
          },
        ],
        type: "reponse",
      },
      {
        id: "49",
        value: "Non",
        id_action: 407,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "50",
    value:
      "Votre organisation assure-t-elle un dialogue avec ses parties prenantes et les communautés impactées ?",
    ids_secteurs: [
      1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23,
      24, 25, 26, 27, 28, 29,
    ],
    id_action: null,
    information:
      "Cette question évalue les pratiques mises en place par votre organisation pour établir un dialogue constructif et régulier avec ses parties prenantes et les communautés affectées par ses activités. Un dialogue efficace est essentiel pour comprendre les préoccupations, les besoins et les attentes de ces groupes, et il contribue à renforcer la transparence, la confiance et la coopération. En favorisant une communication ouverte et inclusive, votre organisation peut mieux ajuster ses stratégies et ses actions en fonction des feedbacks reçus, ce qui renforce son engagement envers la responsabilité sociale et environnementale.",
    children: [
      {
        id: "51",
        value: "Oui",
        id_action: 408,
        done: true,
        information: null,
        children: [
          {
            id: "52",
            value:
              "Comment votre organisation engage-t-elle un dialogue avec ses parties prenantes et les communautés affectées par ses activités ?",
            id_action: null,
            information: null,
            children: [
              {
                id: "53",
                value:
                  "L'entreprise a identifié et cartographié les communautés affectées par ses activités",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "54",
                value:
                  "L'entreprise a élaboré une politique concernant le recensement, l'évaluation, la gestion et la réparation des impacts significatifs sur les communautés concernées",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "55",
                value:
                  "L'entreprise a mis en place des mécanismes de traitement des réclamations",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "56",
                value:
                  "Un comité consultatif composé de parties prenantes est établi et consulté au moins une fois par an",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "57",
                value:
                  "Les parties prenantes internes participent à l'élaboration de la stratégie RSE et des enjeux associés",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "58",
                value:
                  "Les parties prenantes externes sont impliquées dans la définition de la stratégie RSE et des enjeux",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "59",
                value:
                  "L'entreprise a élaboré une matrice de matérialité au cours des quatre dernières années",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "60",
                value:
                  "L'entreprise a élaboré une matrice de double matérialité au cours des quatre dernières années",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "61",
                value: "Autre(s)",
                id_action: null,
                done: false,
                information: null,
                children: [
                  {
                    id: "62",
                    value: "Veuillez préciser :",
                    id_action: null,
                    information: null,
                    children: [],
                    type: "question",
                    inputType: "text",
                    id_kpis: [],
                  },
                ],
                type: "reponse",
              },
            ],
            type: "question",
            inputType: "multiple",
          },
        ],
        type: "reponse",
      },
      {
        id: "64",
        value: "Non",
        id_action: 408,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "65",
    value:
      "Votre entreprise met-elle en place des mesures pour encourager les signalements de comportements non éthiques et prévenir la corruption ?",
    ids_secteurs: [
      1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23,
      24, 25, 26, 27, 28, 29,
    ],
    id_action: null,
    information:
      "Cette question évalue les mécanismes et les politiques que votre entreprise met en place pour permettre aux parties prenantes externes, telles que les clients, fournisseurs ou communautés, de signaler des comportements inappropriés ou contraires à l'éthique. Encourager un environnement de signalement sécurisé et confidentiel est essentiel pour promouvoir une culture d'intégrité et de responsabilité. Cela aide non seulement à identifier et à traiter les problèmes potentiels, mais aussi à renforcer la confiance des parties prenantes dans l'engagement de l'entreprise envers des pratiques durables et éthiques.",
    children: [
      {
        id: "66",
        value: "Oui",
        id_action: 409,
        done: true,
        information: null,
        children: [
          {
            id: "67",
            value: "Quelles sont ces mesures ?",
            id_action: null,
            information: null,
            children: [
              {
                id: "68",
                value: "Formulaire de contact sur le site web de l'entreprise",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "69",
                value:
                  "Adresse e-mail ou ligne téléphoniques spécifiques pour des signalements confidentiels",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "70",
                value: "Boîte à idées pour signalement de problèmes",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "71",
                value: "Formation à l'éthique pour les employés",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "72",
                value: "Gestion des risques et lutte contre la corruption",
                id_action: null,
                done: false,
                information:
                  "Mettre en place des mesures pour évaluer et prévenir les risques de corruption au sein de l'entreprise, tout en assurant la transparence dans toutes les transactions. Cette approche globale aide à anticiper et à atténuer les problèmes potentiels, renforçant ainsi l'intégrité de votre organisation.\n\n👉 Exemple : Effectuer un audit interne régulier pour identifier les zones à risque et établir des procédures claires pour signaler toute tentative de corruption.",
                children: [],
                type: "reponse",
              },
              {
                id: "73",
                value: "Suivi des actions de lobbying",
                id_action: null,
                done: false,
                information:
                  "Consigner les actions que votre entreprise entreprend pour influencer les décisions, comme celles des gouvernements ou d'autres organisations. Cela garantit que vous êtes transparent et honnête dans vos efforts, ce qui aide à établir la confiance avec vos clients et partenaires.\n\n👉 Exemple : Par exemple, si vous participez à des réunions pour présenter vos idées ou si vous financez des études, notez ces activités et les coûts associés, puis partagez ces informations avec vos employés et partenaires pour montrer votre engagement envers la transparence.",
                children: [],
                type: "reponse",
              },
              {
                id: "74",
                value: "Autre(s)",
                id_action: null,
                done: false,
                information: null,
                children: [
                  {
                    id: "75",
                    value: "Veuillez préciser :",
                    id_action: null,
                    information: null,
                    children: [],
                    type: "question",
                    inputType: "text",
                    id_kpis: [],
                  },
                ],
                type: "reponse",
              },
            ],
            type: "question",
            inputType: "multiple",
          },
        ],
        type: "reponse",
      },
      {
        id: "77",
        value: "Non",
        id_action: 409,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "78",
    value:
      "Combien de catégories de parties prenantes sont représentées dans l'organe de gouvernance principal de votre organisation ?",
    ids_secteurs: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 17, 18, 19, 22, 23, 24, 25,
      26, 28, 29,
    ],
    id_action: null,
    information:
      "Cette question vise à déterminer la diversité au sein de l'organe de gouvernance de votre organisation, qui comprend généralement le conseil d'administration et d'autres comités de décision. Il est important que différentes parties prenantes, comme les employés, les clients et les fournisseurs, soient représentées. Cela permet de s'assurer que leurs préoccupations et besoins sont pris en compte, ce qui renforce la responsabilité et la légitimité de l'organisation.",
    children: [
      {
        id: "79",
        value: "0",
        id_action: 410,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
      {
        id: "80",
        value: "1",
        id_action: 410,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
      {
        id: "81",
        value: "2",
        id_action: null,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
      {
        id: "82",
        value: "Plus de 3",
        id_action: null,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
      {
        id: "83",
        value: "La structure juridique de l'entreprise ne le permet pas",
        id_action: null,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "84",
    value:
      "Quels rôles jouent les parties prenantes dans votre processus de décision ?",
    ids_secteurs: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 17, 18, 19, 22, 23, 24, 25,
      26, 28, 29,
    ],
    id_action: null,
    information:
      "Cette question permet d'explorer comment votre organisation intègre les contributions des parties prenantes dans ses décisions. Les parties prenantes peuvent jouer divers rôles, tels que fournir des retours d'expérience, influencer la stratégie, ou participer directement aux discussions. Comprendre leur rôle est essentiel pour évaluer l'inclusivité et la transparence du processus décisionnel, ainsi que pour renforcer la confiance et l'engagement des parties prenantes envers l'organisation. Une approche collaborative favorise une prise de décision plus éclairée et alignée sur les besoins de l'ensemble des parties prenantes.",
    children: [
      {
        id: "85",
        value:
          "Les parties prenantes participent à la prise de décisions stratégiques et ont un droit de vote",
        id_action: null,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
      {
        id: "86",
        value:
          "Les parties prenantes sont consultées et peuvent exprimer leurs opinions",
        id_action: null,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
      {
        id: "87",
        value:
          "Les parties prenantes sont simplement informées des décisions stratégiques",
        id_action: 411,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
      {
        id: "88",
        value:
          "Les parties prenantes ne sont ni informées, ni consultées, ni impliquées dans le processus décisionnel",
        id_action: 411,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "89",
    value: "Votre entreprise s'est-elle dotée d'une raison d'être ?",
    ids_secteurs: [
      1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23,
      24, 25, 26, 27, 28, 29,
    ],
    id_action: null,
    information:
      "Cette question permet d'évaluer si votre entreprise a défini une raison d'être, qui représente son engagement fondamental au-delà du simple profit. Une raison d'être claire guide les décisions stratégiques et opérationnelles de l'entreprise, tout en renforçant son identité et ses valeurs. Elle peut également favoriser l'engagement des employés, la confiance des clients et l'adhésion des parties prenantes, en illustrant comment l'entreprise contribue positivement à la société et à l'environnement.",
    children: [
      {
        id: "90",
        value: "Oui",
        id_action: 415,
        done: true,
        information: null,
        children: [
          {
            id: "91",
            value: "Avez-vous communiqué votre raison d'être ?",
            id_action: null,
            information:
              "Une communication efficace de la raison d'être est essentielle pour assurer que toutes les parties prenantes comprennent les valeurs et les objectifs fondamentaux de l'entreprise. Cela renforce l'engagement, la cohésion et la transparence au sein de l'organisation, tout en permettant aux parties prenantes d'aligner leurs attentes et leurs actions sur la mission et les aspirations de l'entreprise.",
            children: [
              {
                id: "92",
                value: "Oui",
                id_action: null,
                done: true,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "93",
                value: "Non",
                id_action: 412,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
            ],
            type: "question",
            inputType: "single",
          },
          {
            id: "94",
            value:
              "Avez-vous inséré votre raison d'être dans les statuts de votre entreprise ?",
            id_action: null,
            information:
              "Inscrire la raison d'être dans les statuts renforce son importance en tant que fondement des valeurs et des objectifs de l'entreprise. Cela démontre un engagement clair envers cette raison d'être et assure qu'elle est considérée dans toutes les décisions stratégiques. De plus, cette inscription peut renforcer la transparence et la responsabilité, tout en aidant à aligner les actions de l'entreprise avec ses engagements auprès des parties prenantes.",
            children: [
              {
                id: "95",
                value: "Oui",
                id_action: null,
                done: true,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "96",
                value: "Non",
                id_action: 413,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
            ],
            type: "question",
            inputType: "single",
          },
          {
            id: "97",
            value: 'Votre entreprise est-elle "Société à Mission" ?',
            id_action: null,
            information:
              "Cette question vise à évaluer si votre entreprise a obtenu le statut de \"Société à Mission\", un label qui engage formellement l'entreprise à poursuivre des objectifs sociaux et environnementaux tout en continuant à générer des profits. En devenant une Société à Mission, l'entreprise doit définir une raison d'être et des objectifs mesurables qui dépassent le simple intérêt économique. Ce statut favorise la transparence, la responsabilité et l'engagement des parties prenantes, tout en renforçant la crédibilité de l'entreprise dans ses actions pour un impact positif sur la société et l'environnement. Bien que ce statut démontre l'engagement profond d'une entreprise, il est important de souligner que ce statut comporte des obligations contraignantes, nécessitant qu'une vérification de l'atteinte des objectifs soit réalisée par un organisme tiers indépendant (OTI) à la clôture de chaque exercice.",
            children: [
              {
                id: "98",
                value: "Oui",
                id_action: null,
                done: true,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "99",
                value: "Non",
                id_action: 414,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
            ],
            type: "question",
            inputType: "single",
          },
        ],
        type: "reponse",
      },
      {
        id: "100",
        value: "Non",
        id_action: 415,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "101",
    value:
      "Avez-vous mis en place des actions pour faire évoluer votre modèle économique ces dernières années ?",
    ids_secteurs: [
      1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23,
      24, 25, 26, 27, 28, 29,
    ],
    id_action: null,
    information:
      "Cette question permet d'évaluer si votre entreprise a entrepris des initiatives pour adapter ou transformer son modèle économique en réponse aux enjeux actuels, tels que la durabilité, les attentes des consommateurs ou les changements réglementaires. Les actions mises en place peuvent inclure l'innovation de produits, l'adoption de pratiques commerciales plus durables, ou la réévaluation des chaînes d'approvisionnement. Cette évolution est essentielle pour rester compétitif et répondre de manière proactive aux défis économiques et environnementaux contemporains.",
    children: [
      {
        id: "102",
        value: "Oui",
        id_action: 417,
        done: true,
        information: null,
        children: [
          {
            id: "103",
            value: "Quelles sont ces actions ?",
            id_action: null,
            information: null,
            children: [
              {
                id: "104",
                value: "Diversification des produits ou services",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "105",
                value:
                  "Transition vers un modèle d'abonnement ou de services récurrents",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "106",
                value:
                  "Adoption de nouveaux canaux de distribution (en ligne, marketplaces, etc.)",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "107",
                value:
                  "Intégration de solutions numériques pour améliorer l'efficacité opérationnelle",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "108",
                value:
                  "Établissement de partenariats stratégiques avec d'autres entreprises",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "109",
                value: "Passage à un modèle économique circulaire ou durable",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "110",
                value:
                  "Adaptation du modèle commercial aux nouvelles tendances du marché",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "111",
                value:
                  "Révision des politiques de tarification et des modèles de revenus",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "112",
                value: "Autre(s)",
                id_action: null,
                done: false,
                information: null,
                children: [
                  {
                    id: "113",
                    value: "Veuillez préciser :",
                    id_action: null,
                    information: null,
                    children: [],
                    type: "question",
                    inputType: "text",
                    id_kpis: [],
                  },
                ],
                type: "reponse",
              },
            ],
            type: "question",
            inputType: "multiple",
          },
        ],
        type: "reponse",
      },
      {
        id: "115",
        value: "Non",
        id_action: 417,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "116",
    value:
      "Avez-vous mis en œuvre des mesures pour stimuler l'innovation au sein de votre entreprise ?",
    ids_secteurs: [
      1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23,
      24, 25, 26, 27, 28, 29,
    ],
    id_action: null,
    information: null,
    children: [
      {
        id: "117",
        value: "Oui",
        id_action: 418,
        done: true,
        information: null,
        children: [
          {
            id: "118",
            value: "Quelles sont ces mesures ?",
            id_action: null,
            information: null,
            children: [
              {
                id: "119",
                value: "Budget R&D",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "120",
                value:
                  "Investissement dans de nouveaux équipements/technologies",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "121",
                value:
                  "Projets de recherche collaboratifs (avec université, clusters, pôles d'expertise, etc.)",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "122",
                value: "Participation à des événements d'innovation",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "123",
                value: "Dépots de brevets",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "124",
                value: "Formations ou MOOCS liés à l'innovation",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "125",
                value: "Politique d'innovation rédigée",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "126",
                value: "Autre(s)",
                id_action: null,
                done: false,
                information: null,
                children: [
                  {
                    id: "127",
                    value: "Veuillez préciser :",
                    id_action: null,
                    information: null,
                    children: [],
                    type: "question",
                    inputType: "text",
                    id_kpis: [],
                  },
                ],
                type: "reponse",
              },
            ],
            type: "question",
            inputType: "multiple",
          },
        ],
        type: "reponse",
      },
      {
        id: "129",
        value: "Non",
        id_action: 418,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "130",
    value:
      "Avez-vous adopté des pratiques commerciales éthiques pour garantir l'intégrité de vos opérations ?",
    ids_secteurs: [
      1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23,
      24, 25, 26, 27, 28, 29,
    ],
    id_action: null,
    information:
      "Cette question vise à identifier les actions concrètes que votre entreprise a mises en œuvre pour garantir des pratiques éthiques dans ses activités. Ces mesures sont essentielles pour établir la confiance avec vos clients, partenaires et employés, tout en renforçant votre réputation sur le marché.",
    children: [
      {
        id: "131",
        value: "Oui",
        id_action: 419,
        done: true,
        information: null,
        children: [
          {
            id: "132",
            value: "Quelles sont ces pratiques ?",
            id_action: null,
            information: null,
            children: [
              {
                id: "133",
                value: "Affichage clair des prix",
                id_action: null,
                done: false,
                information:
                  "Indiquer les prix de manière transparente pour éviter toute confusion auprès des clients. Un affichage clair aide à instaurer la confiance et à réduire les plaintes liées aux malentendus.\n\n👉 Exemple : Utiliser des étiquettes de prix visibles et détaillées dans vos points de vente et sur votre site web.",
                children: [],
                type: "reponse",
              },
              {
                id: "134",
                value: "Respect des délais et engagements",
                id_action: null,
                done: false,
                information:
                  "Tenir les délais et engagements pris envers les clients/fournisseurs, avec des indicateurs de performance pour le suivi. Cela démontre votre fiabilité et votre professionnalisme.\n\n👉 Exemple : Mettre en place un système de suivi des délais de livraison pour assurer le respect des promesses faites aux clients.",
                children: [],
                type: "reponse",
              },
              {
                id: "135",
                value: "Diffusion d'un code éthique",
                id_action: null,
                done: false,
                information:
                  "Partager un code de conduite ou une charte des affaires avec les clients et fournisseurs avant toute collaboration. Cela établit des attentes claires en matière d'éthique dès le départ.\n\n👉 Exemple : Fournir un document PDF téléchargeable sur votre site, détaillant les valeurs et les principes éthiques de votre entreprise.",
                children: [],
                type: "reponse",
              },
              {
                id: "136",
                value: "Dialogue avec les concurrents",
                id_action: null,
                done: false,
                information:
                  "Participer à des discussions avec d'autres entreprises pour promouvoir des pratiques éthiques au sein de l'industrie. Cela peut favoriser un environnement commercial plus sain.\n\n👉 Exemple : Adhérer à une association professionnelle qui organise des rencontres régulières.",
                children: [],
                type: "reponse",
              },
              {
                id: "137",
                value: "Code de conduite pour les employés",
                id_action: null,
                done: false,
                information:
                  "Avoir un document formel sur les comportements attendus, avec une sensibilisation des employés à son contenu. Cela aide à créer une culture d'intégrité au sein de l'entreprise.\n\n👉 Exemple : Organiser des sessions de discussions régulières pour s'assurer que tous les employés connaissent et comprennent le code de conduite.",
                children: [],
                type: "reponse",
              },
              {
                id: "138",
                value: "Publicité honnête",
                id_action: null,
                done: false,
                information:
                  "S'engager à ne pas induire en erreur les consommateurs par des informations trompeuses dans la publicité. Cela est essentiel pour maintenir la crédibilité et la confiance des clients.\n\n👉 Exemple : Vérifier toutes les revendications faites dans les publicités pour s'assurer qu'elles peuvent être prouvées.",
                children: [],
                type: "reponse",
              },
              {
                id: "139",
                value: "Concurrence loyale",
                id_action: null,
                done: false,
                information:
                  "Respecter les règles du marché et éviter les pratiques déloyales envers les concurrents. Cela contribue à un environnement commercial équitable.\n\n👉 Exemple : S'abstenir de faire des déclarations diffamatoires sur les concurrents dans vos communications marketing.",
                children: [],
                type: "reponse",
              },
              {
                id: "140",
                value: "Formation à l'éthique des ventes",
                id_action: null,
                done: false,
                information:
                  "Former les employés à des pratiques de vente responsables, sans pression déraisonnable. Cela garantit que les interactions avec les clients sont honnêtes et éthiques.\n\n👉 Exemple : Mettre en place un programme de formation qui enseigne des techniques de vente respectueuses et centrées sur le client.",
                children: [],
                type: "reponse",
              },
              {
                id: "141",
                value: "Autre(s)",
                id_action: null,
                done: false,
                information: null,
                children: [
                  {
                    id: "142",
                    value: "Veuillez préciser :",
                    id_action: null,
                    information: null,
                    children: [],
                    type: "question",
                    inputType: "text",
                    id_kpis: [],
                  },
                ],
                type: "reponse",
              },
            ],
            type: "question",
            inputType: "multiple",
          },
        ],
        type: "reponse",
      },
      {
        id: "144",
        value: "Non",
        id_action: 419,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "145",
    value:
      "Avez-vous pris des mesures pour assurer la résilience de votre entreprise ?",
    ids_secteurs: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 17, 18, 19, 22, 23, 24, 25,
      26, 28, 29,
    ],
    id_action: null,
    information:
      "Dans le contexte de la crise écologique actuelle, où les entreprises sont confrontées à des défis sans précédent liés aux changements climatiques, à la pénurie de ressources et à l'évolution des attentes des consommateurs, il est crucial de développer une résilience organisationnelle. Cette question vise à comprendre les actions concrètes que votre entreprise a mises en place pour se préparer à faire face à ces défis et garantir la continuité de ses activités. Une résilience forte permet non seulement de minimiser les impacts négatifs sur l'entreprise, mais aussi de saisir des opportunités pour innover et s'adapter aux nouvelles réalités du marché.",
    children: [
      {
        id: "146",
        value: "Oui",
        id_action: 420,
        done: true,
        information: null,
        children: [
          {
            id: "147",
            value: "Quelles sont ces mesures ?",
            id_action: null,
            information: null,
            children: [
              {
                id: "148",
                value:
                  "Indicateurs d'alerte, évaluations des risques et évaluations de la résilience",
                id_action: null,
                done: false,
                information:
                  "Réaliser des analyses pour identifier les risques environnementaux et opérationnels qui pourraient affecter l'entreprise. Cela permet d'anticiper les problèmes potentiels et de prendre des mesures préventives.\n\n👉 Exemple : Effectuer des audits réguliers pour évaluer les vulnérabilités liées aux conditions climatiques.",
                children: [],
                type: "reponse",
              },
              {
                id: "149",
                value: "Analyse Swot",
                id_action: null,
                done: false,
                information:
                  "Réaliser une analyse SWOT (forces, faiblesses, opportunités, menaces) pour évaluer la position actuelle de l'entreprise et identifier les domaines d'amélioration. Cela permet de prendre des décisions éclairées pour renforcer la résilience.\n\n👉 Exemple : Organiser des sessions avec l'équipe de direction pour passer en revue les éléments de l'analyse SWOT et définir des stratégies basées sur les résultats.",
                children: [],
                type: "reponse",
              },
              {
                id: "150",
                value: "Planification stratégique formalisée/veille",
                id_action: null,
                done: false,
                information:
                  "Élaborer un plan stratégique clair qui inclut une veille constante sur les tendances du marché, les réglementations et les enjeux environnementaux. Cela aide à anticiper les changements et à ajuster les stratégies en conséquence.\n\n👉 Exemple : Mettre en place un calendrier de révisions stratégiques régulières pour s'assurer que le plan reste pertinent.",
                children: [],
                type: "reponse",
              },
              {
                id: "151",
                value: "Plan de gestion de crises",
                id_action: null,
                done: false,
                information:
                  "Créer un plan détaillé pour réagir rapidement et efficacement en cas de crise, afin de minimiser les impacts sur l'entreprise. Ce plan doit être régulièrement mis à jour et testé.\n\n👉 Exemple : Développer des scénarios de crise et des protocoles d'action, avec des rôles et responsabilités clairement définis.",
                children: [],
                type: "reponse",
              },
              {
                id: "152",
                value: "Audits",
                id_action: null,
                done: false,
                information:
                  "Effectuer des audits réguliers pour évaluer la conformité aux normes et l'efficacité des processus en place. Cela permet d'identifier les lacunes et de mettre en œuvre des améliorations nécessaires.\n\n👉 Exemple : Réaliser des audits internes semestriels pour vérifier les pratiques de gestion des risques.",
                children: [],
                type: "reponse",
              },
              {
                id: "153",
                value:
                  "Adhésion de l'entreprise à des instances professionnelles",
                id_action: null,
                done: false,
                information:
                  "S'inscrire au sein d'organisations professionnelles liées aux enjeux de durabilité et de responsabilité sociétale. Cela permet de rester informé des meilleures pratiques et des évolutions réglementaires.\n\n👉 Exemple : Devenir membre d'une association qui promeut les normes de durabilité dans votre secteur d'activité.",
                children: [],
                type: "reponse",
              },
              {
                id: "154",
                value: "Participation à l'élaboration de normes",
                id_action: null,
                done: false,
                information:
                  "Contribuer à la création de solutions et de normes sur les enjeux de durabilité au sein des organisations professionnelles de votre secteur. Cela montre un engagement à améliorer les pratiques dans l'industrie.\n\n👉 Exemple : Participer à des groupes de travail ou des comités pour développer des lignes directrices sur la durabilité.",
                children: [],
                type: "reponse",
              },
              {
                id: "155",
                value: "Plan de continuité d'activité",
                id_action: null,
                done: false,
                information:
                  "Établir un plan pour assurer le bon fonctionnement de l'entreprise en cas de crise majeure (comme une pandémie ou une catastrophe naturelle). Cela aide à maintenir les opérations essentielles.\n\n👉 Exemple : Créer un document qui décrit les procédures à suivre en cas de crise et former le personnel à ces procédures.",
                children: [],
                type: "reponse",
              },
              {
                id: "156",
                value: "Diversification des sources d'approvisionnement",
                id_action: null,
                done: false,
                information:
                  "Travailler avec plusieurs fournisseurs pour réduire la dépendance à un seul, ce qui permet d'assurer la continuité des approvisionnements même en cas de perturbation.\n\n👉 Exemple : Identifier et établir des relations avec plusieurs fournisseurs pour des matières premières clés.",
                children: [],
                type: "reponse",
              },
              {
                id: "157",
                value: "Collaboration avec la communauté locale",
                id_action: null,
                done: false,
                information:
                  "S'engager avec la communauté et d'autres acteurs locaux pour renforcer la capacité d'adaptation face aux enjeux environnementaux. Cela favorise un soutien mutuel.\n\n👉 Exemple : Participer à des projets communautaires axés sur la durabilité ou le développement économique local.",
                children: [],
                type: "reponse",
              },
              {
                id: "158",
                value:
                  "Protection des données et de l'infrastructure informatique",
                id_action: null,
                done: false,
                information:
                  "Mettre en place des mesures de sécurité pour protéger les données sensibles et l'infrastructure informatique contre les cyberattaques. Cela est crucial dans le contexte numérique actuel.\n\n👉 Exemple : Utiliser des logiciels de sécurité avancés et former les employés à la cybersécurité.",
                children: [],
                type: "reponse",
              },
              {
                id: "159",
                value: "Stock de matières premières",
                id_action: null,
                done: false,
                information:
                  "Maintenir un inventaire de matières premières ou de produits finis pour faire face à d'éventuelles ruptures d'approvisionnement. Cela permet de continuer les opérations même en période de crise.\n\n👉 Exemple : Constituer un stock de sécurité pour les matières essentielles afin d'éviter les ruptures.",
                children: [],
                type: "reponse",
              },
              {
                id: "160",
                value: "Trésorerie de réserve",
                id_action: null,
                done: false,
                information:
                  "Avoir des fonds disponibles pour faire face à des périodes d'activité réduite ou à des dépenses imprévues. Cela offre une marge de manœuvre financière en cas de besoin.\n\n👉 Exemple : Créer un fonds d'urgence équivalent à plusieurs mois de dépenses d'exploitation.",
                children: [],
                type: "reponse",
              },
              {
                id: "161",
                value: "Partenariats/réseaux de collaboration",
                id_action: null,
                done: false,
                information:
                  "Établir des collaborations avec d'autres entreprises pour partager des ressources et des bonnes pratiques. Cela renforce la résilience collective.\n\n👉 Exemple : Former des alliances avec d'autres entreprises pour échanger des connaissances et des ressources en cas de besoin.",
                children: [],
                type: "reponse",
              },
              {
                id: "162",
                value: "Autre(s)",
                id_action: null,
                done: false,
                information: null,
                children: [
                  {
                    id: "163",
                    value: "Veuillez préciser :",
                    id_action: null,
                    information: null,
                    children: [],
                    type: "question",
                    inputType: "text",
                    id_kpis: [],
                  },
                ],
                type: "reponse",
              },
            ],
            type: "question",
            inputType: "multiple",
          },
        ],
        type: "reponse",
      },
      {
        id: "165",
        value: "Non",
        id_action: 420,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "166",
    value: "Quel type de management caractérise le mieux votre entreprise ?",
    ids_secteurs: [
      1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23,
      24, 25, 26, 27, 28, 29,
    ],
    id_action: null,
    information:
      "Cette question vise à identifier le style de management prédominant au sein de votre entreprise. Le type de management a un impact significatif sur la culture organisationnelle, la motivation des employés et l'efficacité opérationnelle. En comprenant votre approche managériale, vous pouvez mieux évaluer comment les décisions sont prises, comment les équipes collaborent et comment l'entreprise s'adapte aux changements du marché. Cela peut également révéler les forces et les faiblesses de votre structure organisationnelle, permettant ainsi de déterminer des pistes d'amélioration pour renforcer la performance globale de l'entreprise.",
    children: [
      {
        id: "167",
        value: "Structure verticale",
        id_action: 421,
        done: false,
        information:
          "Une approche où la hiérarchie est clairement définie, avec des décisions prises par la direction et communiquées aux employés. C'est simple et efficace pour les petites équipes.\n\n👉 Exemple : Les gestionnaires prennent des décisions et transmettent les instructions aux employés.",
        children: [],
        type: "reponse",
      },
      {
        id: "168",
        value: "Structure mixte",
        id_action: null,
        done: false,
        information:
          "Une combinaison de hiérarchie et d'inclusion, où les managers consultent leurs équipes tout en gardant une certaine structure. Cela permet d'entendre différentes voix tout en maintenant l'ordre.\n\n👉 Exemple : Les responsables de service consultent leurs équipes pour des retours avant de finaliser des décisions.",
        children: [],
        type: "reponse",
      },
      {
        id: "169",
        value: "Structure interconnectée",
        id_action: null,
        done: false,
        information:
          "Un modèle où les équipes collaborent et s'adaptent rapidement aux changements. L'accent est mis sur la motivation par les objectifs communs.\n\n👉 Exemple : Les équipes se regroupent pour travailler sur des projets spécifiques, ajustant leur approche selon les retours.",
        children: [],
        type: "reponse",
      },
      {
        id: "170",
        value: "Structure aplatie",
        id_action: null,
        done: false,
        information:
          "Peu de niveaux hiérarchiques, favorisant la participation de tous dans la définition des objectifs. Cela encourage la collaboration et la responsabilité partagée.\n\n👉 Exemple : Les employés participent à des réunions pour définir ensemble les priorités de l'équipe.",
        children: [],
        type: "reponse",
      },
      {
        id: "171",
        value: "Structure horizontale",
        id_action: null,
        done: false,
        information:
          "Moins de niveaux hiérarchiques, permettant aux employés de travailler ensemble de manière autonome et collaborative.\n\n👉 Exemple : Les équipes sont encouragées à prendre des décisions ensemble sans intervention constante de la direction.",
        children: [],
        type: "reponse",
      },
      {
        id: "172",
        value: "Structure agile",
        id_action: null,
        done: false,
        information:
          "Un modèle flexible qui permet à l'entreprise de s'adapter rapidement aux besoins du marché. Les équipes se forment autour de projets et peuvent changer selon les priorités.\n\n👉 Exemple : Créer des équipes temporaires pour répondre à des besoins spécifiques, puis les réorganiser selon les nouveaux projets.",
        children: [],
        type: "reponse",
      },
      {
        id: "173",
        value: "Autre(s)",
        id_action: null,
        done: false,
        information: null,
        children: [
          {
            id: "174",
            value: "Veuillez préciser :",
            id_action: null,
            information: null,
            children: [],
            type: "question",
            inputType: "text",
            id_kpis: [],
          },
        ],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "176",
    value:
      "Votre entreprise a-t-elle été condamnée au cours des 3 dernières années ?",
    ids_secteurs: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 17, 18, 19, 22, 23, 24, 25,
      26, 28, 29,
    ],
    id_action: null,
    information:
      "Cette question vise à évaluer si votre entreprise a rencontré des problèmes juridiques ou éthiques au cours des trois dernières années. Les condamnations peuvent avoir des répercussions significatives sur la réputation, la performance et la conformité de l'entreprise. En identifiant ces condamnations, vous pouvez mieux comprendre les risques associés à vos pratiques et déterminer les domaines nécessitant une attention particulière. Cela reflète également l'engagement de votre entreprise envers la transparence et la responsabilité vis-à-vis des parties prenantes, qu'il s'agisse d'employés, de clients ou de partenaires commerciaux.",
    children: [
      {
        id: "177",
        value: "Oui",
        id_action: 422,
        done: true,
        information: null,
        children: [
          {
            id: "178",
            value: "Pour quelles raisons ?",
            id_action: null,
            information: null,
            children: [
              {
                id: "179",
                value: "Condamnations aux prud'hommes",
                id_action: null,
                done: false,
                information:
                  "Cela concerne les décisions judiciaires prises par le conseil de prud'hommes en cas de litige entre employeurs et employés, souvent liés à des questions de licenciement, de harcèlement ou de conditions de travail.\n\n👉 Exemple : Une décision qui remet en question le licenciement d'un employé pour non-respect des procédures.",
                children: [],
                type: "reponse",
              },
              {
                id: "180",
                value: "Violation des droits humains",
                id_action: null,
                done: false,
                information:
                  "Cela inclut des infractions aux droits fondamentaux des individus, comme le travail des enfants ou le travail forcé. Ces violations peuvent porter atteinte à la réputation de l'entreprise et entraîner des conséquences juridiques.\n\n👉 Exemple : Être accusé d'exploiter des enfants dans la chaîne d'approvisionnement.",
                children: [],
                type: "reponse",
              },
              {
                id: "181",
                value: "Fraude fiscale et pratiques anticoncurrentielles",
                id_action: null,
                done: false,
                information:
                  "Cela englobe les comportements illégaux liés à l'évasion fiscale ou à des pratiques qui nuisent à la concurrence loyale sur le marché, comme la manipulation des prix.\n\n👉 Exemple : Utiliser une société écran pour éviter de payer des impôts.",
                children: [],
                type: "reponse",
              },
              {
                id: "182",
                value: "Opération dans des zones de conflits",
                id_action: null,
                done: false,
                information:
                  "Cela concerne le fonctionnement d'une entreprise dans des régions où il y a des conflits armés, ce qui peut poser des risques éthiques et légaux.\n\n👉 Exemple : Exploiter des ressources dans une région en guerre, sans garantir la sécurité des employés.",
                children: [],
                type: "reponse",
              },
              {
                id: "183",
                value: "Violation des données personnelles",
                id_action: null,
                done: false,
                information:
                  "Cela fait référence à des infractions liées à la gestion des informations personnelles, comme la perte de données sensibles ou la revente illégale de données.\n\n👉 Exemple : Être sanctionné pour avoir divulgué des informations personnelles de clients sans consentement.",
                children: [],
                type: "reponse",
              },
              {
                id: "184",
                value: "Atteinte aux droits des travailleurs",
                id_action: null,
                done: false,
                information:
                  "Cela inclut des violations liées aux droits fondamentaux des employés, comme le droit de grève, le droit d'association ou la discrimination.\n\n👉 Exemple : Être condamné pour avoir empêché des employés de former un syndicat.",
                children: [],
                type: "reponse",
              },
              {
                id: "185",
                value: "Sanctions environnementales",
                id_action: null,
                done: false,
                information:
                  "Cela concerne les pénalités imposées pour non-respect des réglementations environnementales, ce qui peut avoir des répercussions sur la réputation et les opérations de l'entreprise.\n\n👉 Exemple : Avoir été sanctionné pour pollution des eaux.",
                children: [],
                type: "reponse",
              },
              {
                id: "186",
                value:
                  "Faillite d'une filiale ou licenciement de plus de 20 % des employés",
                id_action: null,
                done: false,
                information:
                  "Cela fait référence à des situations critiques où une filiale de l'entreprise fait faillite ou où une grande partie du personnel est licenciée, ce qui peut affecter la stabilité de l'entreprise.\n\n👉 Exemple : Licencier 30 % des employés en raison de difficultés financières.",
                children: [],
                type: "reponse",
              },
            ],
            type: "question",
            inputType: "multiple",
          },
        ],
        type: "reponse",
      },
      {
        id: "187",
        value: "Non",
        id_action: 422,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "188",
    value:
      "Selon quelles conditions votre entreprise paie-t-elle ses fournisseurs ?",
    ids_secteurs: [
      1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23,
      24, 25, 26, 27, 28, 29,
    ],
    id_action: null,
    information:
      "Cette question vise à comprendre les modalités de paiement que votre entreprise applique lors de ses transactions avec ses fournisseurs. Une gestion claire et efficace des paiements peut contribuer à maintenir des relations solides et de confiance avec vos partenaires commerciaux.",
    children: [
      {
        id: "189",
        value: "A réception de facture",
        id_action: null,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
      {
        id: "190",
        value: "Sous 30 jours",
        id_action: null,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
      {
        id: "191",
        value: "Sous 30 jours, fin de mois",
        id_action: null,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
      {
        id: "192",
        value: "Sous 45 jours",
        id_action: 423,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
      {
        id: "193",
        value: "Sous 45 jours, fin de mois",
        id_action: 423,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
      {
        id: "194",
        value: "Plus de 45 jours fin de mois",
        id_action: 423,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "195",
    value:
      "De quelle manière votre entreprise pilote-t-elle sa performance sociale et environnementale ?",
    ids_secteurs: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 17, 18, 19, 22, 23, 24, 25,
      26, 28, 29,
    ],
    id_action: null,
    information:
      "Cette question vise à comprendre comment votre entreprise intègre des critères sociaux et environnementaux dans son processus de prise de décision. Cela inclut l'utilisation de pratiques telles que la mise en place d'un comité RSE, la désignation d'un ambassadeur RSE, l'élaboration d'une charte RSE, l'utilisation d'indicateurs de performance RSE et la rédaction d'un reporting RSE.",
    children: [
      {
        id: "196",
        value: "Comité RSE",
        id_action: null,
        done: false,
        information:
          "Un groupe de travail chargé de définir, suivre et promouvoir les initiatives de responsabilité sociétale au sein de l'entreprise.",
        children: [],
        type: "reponse",
      },
      {
        id: "197",
        value: "Ambassadeur RSE",
        id_action: null,
        done: false,
        information:
          "Un employé désigné pour représenter et promouvoir les valeurs et les actions liées à la responsabilité sociétale dans l'organisation.",
        children: [],
        type: "reponse",
      },
      {
        id: "198",
        value: "Charte RSE",
        id_action: null,
        done: false,
        information:
          "Un document formel qui définit les engagements et les principes de l'entreprise en matière de responsabilité sociale et environnementale.",
        children: [],
        type: "reponse",
      },
      {
        id: "199",
        value: "Indicateurs de performance RSE",
        id_action: null,
        done: false,
        information:
          "Des mesures utilisées pour évaluer l'efficacité et l'impact des initiatives de responsabilité sociétale de l'entreprise.",
        children: [],
        type: "reponse",
      },
      {
        id: "200",
        value: "Reporting RSE",
        id_action: null,
        done: false,
        information:
          "Le processus de communication des résultats et des progrès réalisés par l'entreprise en matière de responsabilité sociétale, souvent sous la forme d'un rapport annuel.",
        children: [],
        type: "reponse",
      },
      {
        id: "201",
        value: "Autre(s)",
        id_action: null,
        done: false,
        information: null,
        children: [
          {
            id: "202",
            value: "Veuillez préciser :",
            id_action: null,
            information: null,
            children: [],
            type: "question",
            inputType: "text",
            id_kpis: [],
          },
        ],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "multiple",
  },
  {
    id: "204",
    value:
      "Avez-vous rédigé une politique d'achats responsables au sein de votre entreprise ?",
    ids_secteurs: [
      1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23,
      24, 25, 26, 27, 28, 29,
    ],
    id_action: null,
    information:
      "Cette question vise à déterminer si votre entreprise a mis en place une Politique d'achats responsables, qui définit les principes et les critères à suivre lors des décisions d'achat et d'approvisionnement. Une telle politique est essentielle pour intégrer des considérations sociales, environnementales et éthiques dans le processus d'achat. Elle peut inclure des engagements à favoriser des fournisseurs respectant des normes éthiques, à minimiser l'impact environnemental des produits achetés et à garantir la transparence dans les pratiques d'approvisionnement. L'élaboration d'une politique d'achats responsables témoigne de l'engagement de votre entreprise envers la durabilité et la responsabilité sociale, tout en renforçant la confiance des parties prenantes.",
    children: [
      {
        id: "205",
        value: "Oui",
        id_action: 424,
        done: true,
        information: null,
        children: [],
        type: "reponse",
      },
      {
        id: "206",
        value: "Non",
        id_action: 424,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "207",
    value: "Avez-vous rédigé et communiqué un questionnaire RSE fournisseur ?",
    ids_secteurs: [
      1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23,
      24, 25, 26, 27, 28, 29,
    ],
    id_action: null,
    information:
      "Cette question vise à savoir si votre entreprise a élaboré un questionnaire RSE destiné à ses fournisseurs, qui permet d'évaluer divers aspects de leurs pratiques et de leur conformité aux exigences de l'entreprise. Un tel questionnaire peut couvrir des sujets tels que les normes de qualité, les pratiques environnementales, le respect des droits des travailleurs et les conditions de travail. La communication de ce questionnaire aux fournisseurs est essentielle pour établir des attentes claires et garantir que ceux-ci adhèrent aux valeurs et aux normes de votre entreprise. En intégrant un questionnaire fournisseur dans votre processus d'approvisionnement, vous pouvez améliorer la transparence, renforcer la responsabilité et favoriser des relations de confiance avec vos partenaires commerciaux.",
    children: [
      {
        id: "208",
        value: "Oui",
        id_action: 425,
        done: true,
        information: null,
        children: [
          {
            id: "209",
            value:
              "Quelle est la part des réponses conformes parmi les réponses reçues au questionnaire RSE fournisseur ?",
            id_action: null,
            information: null,
            children: [],
            type: "question",
            inputType: "numeric",
            id_kpis: [341],
          },
          {
            id: "211",
            value:
              "Quelle est la part des réponses conformes parmi les réponses reçues au questionnaire RSE fournisseur ?",
            id_action: null,
            information: null,
            children: [],
            type: "question",
            inputType: "numeric",
            id_kpis: [342],
          },
        ],
        type: "reponse",
      },
      {
        id: "213",
        value: "Non",
        id_action: 425,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
  {
    id: "214",
    value: "Y-a-t-il des actionnaires au sein de votre entreprise ?",
    ids_secteurs: [
      1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23,
      24, 25, 26, 27, 28, 29,
    ],
    id_action: null,
    information:
      "Cette question cherche à savoir si votre entreprise compte des actionnaires. La présence d'actionnaires peut indiquer la structure de propriété de l'entreprise et son engagement envers les investisseurs, influençant ainsi les décisions stratégiques et la distribution des bénéfices.",
    children: [
      {
        id: "215",
        value: "Oui",
        id_action: null,
        done: true,
        information: null,
        children: [
          {
            id: "216",
            value:
              "Votre organisation reverse-t-elle des dividendes à ses actionnaires ?",
            id_action: null,
            information:
              "Cette question vise à déterminer si votre entreprise distribue une partie de ses bénéfices sous forme de dividendes à ses actionnaires. La réponse à cette question peut fournir des informations sur la santé financière de l'entreprise, sa stratégie de gestion des bénéfices et son engagement envers ses investisseurs. Cela peut également indiquer si l'entreprise privilégie la distribution de profits immédiats ou le réinvestissement pour soutenir sa croissance à long terme.",
            children: [
              {
                id: "217",
                value: "Oui",
                id_action: null,
                done: true,
                information: null,
                children: [
                  {
                    id: "218",
                    value:
                      "Quelle est la part des bénéfices de l'organisation qui ont été reversés sous forme de dividendes aux actionnaires au cours de 12 derniers mois ?",
                    id_action: null,
                    information:
                      "Cette question évalue le pourcentage des bénéfices de l'entreprise distribués à ses actionnaires sous forme de dividendes, reflétant sa politique de rémunération des investisseurs.",
                    children: [
                      {
                        id: "219",
                        value: "Plus de 75%",
                        id_action: null,
                        done: false,
                        information: null,
                        children: [],
                        type: "reponse",
                      },
                      {
                        id: "220",
                        value: "50 à 74%",
                        id_action: null,
                        done: false,
                        information: null,
                        children: [],
                        type: "reponse",
                      },
                      {
                        id: "221",
                        value: "40 à 49%",
                        id_action: null,
                        done: false,
                        information: null,
                        children: [],
                        type: "reponse",
                      },
                      {
                        id: "222",
                        value: "20 à 39%",
                        id_action: null,
                        done: false,
                        information: null,
                        children: [],
                        type: "reponse",
                      },
                      {
                        id: "223",
                        value: "Moins de 20%",
                        id_action: null,
                        done: false,
                        information: null,
                        children: [],
                        type: "reponse",
                      },
                    ],
                    type: "question",
                    inputType: "single",
                  },
                ],
                type: "reponse",
              },
              {
                id: "224",
                value: "Non",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
            ],
            type: "question",
            inputType: "single",
          },
          {
            id: "225",
            value:
              "Quelle est la part du capital de votre entreprise qui est détenue par des actionnaires (hors dirigeants) ?",
            id_action: null,
            information:
              "Cette question vise à déterminer le pourcentage du capital de votre entreprise qui est détenu par des actionnaires autres que les dirigeants. Cela permet d'évaluer la structure de propriété de l'entreprise et d'analyser l'implication des investisseurs externes dans la gestion et la prise de décision.",
            children: [
              {
                id: "226",
                value: "Moins de 5%",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "227",
                value: "Entre 5% et 19,9%",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "228",
                value: "Entre 20% et 29,9%",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
              {
                id: "229",
                value: "Plus de 30%",
                id_action: null,
                done: false,
                information: null,
                children: [],
                type: "reponse",
              },
            ],
            type: "question",
            inputType: "single",
          },
        ],
        type: "reponse",
      },
      {
        id: "230",
        value: "Non",
        id_action: null,
        done: false,
        information: null,
        children: [],
        type: "reponse",
      },
    ],
    type: "question",
    inputType: "single",
  },
];
