import { z } from "zod"

export const completeProfileSchema = z.object({
  // Company information
  raison_sociale: z.string().min(1, "La raison sociale est requise"),
  tel: z.string().min(1, "Le numéro de téléphone est requis"),
  siren: z.string().min(1, "Le SIREN est requis"),
  adresse: z.string().min(1, "L'adresse est requise"),
  annee_de_creation: z.number().min(1800, "Année invalide").max(new Date().getFullYear(), "L'année ne peut pas être dans le futur"),
  
  // Labels (stored as array of label IDs)
  labels: z.array(z.number()).optional(),
  
  // Sector (stored as sector ID)
  secteur_principal: z.string().min(1, "Le secteur principal est requis"),
  sous_secteur: z.string().min(1, "Le sous-secteur est requis"),
  
  // User function
  fonction: z.string().min(1, "La fonction est requise"),
})

export type CompleteProfileFormData = z.infer<typeof completeProfileSchema>

export const completeProfileFormData = [
  {
    formName: "Information sur votre entreprise",
    formType: "input",
    content: [
      {
        label: "Raison sociale",
        type: "text",
        placeholder: "entrez votre raison sociale",
        name: "raison_sociale",
      },
      {
        label: "Numéro de téléphone",
        type: "tel",
        placeholder: "06 XX XX XX XX",
        name: "tel",
      },
      {
        label: "SIREN",
        type: "text",
        placeholder: "entrez votre SIREN",
        name: "siren",
      },
      {
        label: "Année de création",
        type: "number",
        placeholder: "entrez l'année de création",
        name: "annee_de_creation",
      },
    ],
  },
  {
    formName: "Indiquez nous vos labels",
    formType: "checkbox",
    name: "labels",
    content: [
      { id: 1, label: "1 % for the Planet" },
      { id: 2, label: "Approvisionnement Responsable (UEBT)" },
      { id: 3, label: "Artisan Socialement Responsable" },
      { id: 4, label: "B Corp" },
      { id: 5, label: "Bas Carbone" },
      { id: 6, label: "Bâtiment BREEAM" },
      { id: 7, label: "Bâtiment HQE" },
      { id: 8, label: "Bâtiment LEED" },
      { id: 9, label: "Bee Friendly" },
      { id: 10, label: "Biodiversity Progress (LUCIE)" },
      { id: 11, label: "Carbon Trust Standard" },
      { id: 12, label: "Certificat EcoEntreprise" },
      { id: 13, label: "Choose My Company" },
      { id: 14, label: "Clef Verte" },
      { id: 15, label: "Climate Neutral Certified" },
      { id: 16, label: "Coopératives So Responsables" },
      { id: 17, label: "Coq Vert" },
      { id: 18, label: "Cradle to Cradle" },
      { id: 19, label: "Diversité (AFNOR)" },
      { id: 20, label: "Ecodynamic Company" },
      { id: 21, label: "Écogîte" },
      { id: 22, label: "Écotable" },
      { id: 23, label: "EcoVadis" },
      { id: 24, label: "Égalité (AFNOR)" },
      { id: 25, label: "Empl'itude" },
      { id: 26, label: "Engagé RSE" },
      { id: 27, label: "Entreprise / Territoire Engagé pour la Nature" },
      { id: 28, label: "Entreprise du Patrimoine Vivant" },
      { id: 29, label: "Entreprise socialement responsable" },
      { id: 30, label: "EnVol (Agence LUCIE)" },
      { id: 31, label: "ESS ADN" },
      { id: 32, label: "Ethibel" },
      { id: 33, label: "European Plastics Pact" },
      { id: 34, label: "Food Index for Good" },
      { id: 35, label: "France Terre Textile" },
      { id: 36, label: "Gîtes Panda" },
      { id: 37, label: "GLOBALG.A.P" },
      { id: 38, label: "Great Place to Work France" },
      { id: 39, label: "Green Key" },
      { id: 40, label: "Greenfin" },
      { id: 41, label: "Greentech Innovation" },
      { id: 42, label: "Haute Valeur Environnementale" },
      { id: 43, label: "Human for Client" },
      { id: 44, label: "Initiative Remarquable" },
      { id: 45, label: "ISO 14001" },
      { id: 46, label: "ISO 50001" },
      { id: 47, label: "ISO 9001" },
      { id: 48, label: "ISR" },
      { id: 49, label: "Le Lion Bleu" },
      { id: 50, label: "LEAF Marque" },
      { id: 51, label: "LUCIE 26000" },
      { id: 52, label: "LUCIE Positive" },
      { id: 53, label: "LUCIE Progress" },
      { id: 54, label: "Made in Respect" },
      { id: 55, label: "Mon coiffeur s'engage" },
      { id: 56, label: "Numérique Responsable (Lucie)" },
      { id: 57, label: "Optic for Good" },
      { id: 58, label: "Pêche Durable" },
      { id: 59, label: "PME+" },
      { id: 60, label: "Positive Company" },
      { id: 61, label: "Prestadd" },
      { id: 62, label: "Print'Ethic" },
      { id: 63, label: "Production 100 % Locale" },
      { id: 64, label: "Proprement Engagés" },
      { id: 65, label: "Responsabilité et Santé" },
      { id: 66, label: "Responsible Care" },
      { id: 67, label: "RGE" },
      { id: 68, label: "RSE Agences Actives" },
      { id: 69, label: "RSE de la FNB" },
      { id: 70, label: "RSEi" },
      { id: 71, label: "SBTI" },
      { id: 72, label: "SCOP BTP RSE" },
      { id: 73, label: "SloWeAre" },
      { id: 74, label: "Solar Impulse" },
      { id: 75, label: "Startup Engagée" },
      { id: 76, label: "Terra Vitis" },
      { id: 77, label: "Territoires Engagés pour la Nature" },
      { id: 78, label: "THQSE" },
      { id: 79, label: "TopSite" },
      { id: 80, label: "Tourisme & Handicap" },
      { id: 81, label: "Tourisme Équitable" },
      { id: 82, label: "United Nations Global Compact" },
      { id: 83, label: "Vergers Écoresponsables" },
      { id: 84, label: "Vignerons Engagés" },
      { id: 85, label: "Votre Institut Responsable pour une Beauté Durable" },
      { id: 86, label: "WFTO" },
      { id: 87, label: "World's Most Ethical Companies" },
      { id: 88, label: "Zéro Déforestation" },
    ],
  },
  {
    formName: "Votre secteur",
    formType: "select",
    name: "secteur",
    content: {
      label: "Choisissez votre secteur",
      placeholder: "secteur",
      options: [
        {
          value: "1",
          label: "Alimentation, agriculture et élevage",
          children: [
            { value: "1", label: "Agriculture & production agricole" },
            { value: "2", label: "Agriculture urbaine" },
            { value: "3", label: "Alimentation pour animaux" },
            { value: "4", label: "Bières & brasseries" },
            { value: "5", label: "Boissons, sodas, jus & fontaines" },
            { value: "6", label: "Cafés, infusions & herboristerie" },
            { value: "7", label: "Céréales & produits céréaliers" },
            { value: "8", label: "Commerce alimentaire" },
            { value: "9", label: "Fruits, légumes & fruits secs" },
            { value: "10", label: "Grossiste alimentaire" },
            { value: "11", label: "Marketplace alimentaire" },
            { value: "12", label: "Produits alimentaires transformés" },
            { value: "13", label: "Produits boulangers, pâtissiers et biscuiteries" },
            { value: "14", label: "Produits laitiers" },
            { value: "15", label: "Vins, Champagnes & Vignerons" },
          ],
        },
        {
          value: "2",
          label: "Arts, cinéma, culture",
          children: [
            { value: "16", label: "Centres culturels" },
            { value: "17", label: "Librairies & librairies en ligne" },
            { value: "18", label: "Salles de spectacle & théâtres" },
          ],
        },
        {
          value: "4",
          label: "Audit, gestion, conseil, droit",
          children: [
            { value: "20", label: "Cabinet comptable et d'audit" },
            { value: "21", label: "Cabinet de conseil" },
            { value: "22", label: "Cabinet juridique" },
          ],
        },
        {
          value: "5",
          label: "Automobiles, véhicules",
          children: [
            { value: "23", label: "Concession automobile, réparation véhicule et pneumatiques" },
            { value: "24", label: "Deux-roues & véhicules légers" },
            { value: "25", label: "Location & vente de bateaux" },
            { value: "26", label: "Location & vente de scooters et motos" },
            { value: "27", label: "Location & vente de vélos et trottinettes" },
            { value: "28", label: "Location & vente de voitures" },
            { value: "29", label: "Réparation, maintenance & aménagement de véhicules" },
            { value: "30", label: "Véhicules lourds & utilitaires" },
            { value: "31", label: "Véhicules tractés" },
          ],
        },
        {
          value: "6",
          label: "Banque, assurance, finance, fintech",
          children: [
            { value: "32", label: "Agent général d'assurance" },
            { value: "33", label: "Assurance & Mutuelle" },
            { value: "34", label: "Courtage bancaire et d'assurance" },
            { value: "35", label: "Plateforme de financement" },
          ],
        },
        {
          value: "7",
          label: "Commerce, distribution, négoce",
          children: [
            { value: "36", label: "Centrale d'achat et de référencement" },
            { value: "37", label: "Commerce divers" },
            { value: "38", label: "Gestion de distributeurs automatiques" },
            { value: "39", label: "Import-export & négoce" },
            { value: "40", label: "Marketplace & plateforme de e-commerce" },
            { value: "41", label: "Produits divers" },
          ],
        },
        {
          value: "8",
          label: "Communication, marketing et audiovisuel",
          children: [
            { value: "42", label: "Agence de communication & marketing" },
            { value: "43", label: "Agence de relation publique et de lobbying" },
            { value: "44", label: "Agence de relations presse & régies publicitaires" },
            { value: "45", label: "Objets promotionnels & cadeaux d'entreprise" },
            { value: "46", label: "Production audiovisuelle & graphisme" },
          ],
        },
        {
          value: "9",
          label: "Construction, travaux publics, immobilier, architecture",
          children: [
            { value: "47", label: "Agent immobilier" },
            { value: "48", label: "Aménagement & entretien d'extérieur" },
            { value: "49", label: "Aménagement & entretien d'intérieur" },
            { value: "50", label: "Bureau d'étude immobilier" },
            { value: "51", label: "Construction & Travaux publics" },
            { value: "52", label: "Contractant général & maître d'œuvre" },
            { value: "53", label: "Espaces de coworking & espaces partagés" },
            { value: "54", label: "Foncière & gestion immobilière" },
            { value: "55", label: "Gestionnaire de co-living" },
            { value: "56", label: "Matériaux de construction" },
            { value: "57", label: "Promotion immobilière" },
          ],
                 },
         {
           value: "10",
           label: "Cosmétique, hygiène, bien-être",
           children: [
             { value: "58", label: "Coiffeurs & Barbiers" },
             { value: "59", label: "Cosmétiques, soins & parfums" },
             { value: "60", label: "Instituts de beauté & de bien-être" },
             { value: "61", label: "Produits d'hygiène" },
           ],
         },
         {
           value: "11",
           label: "Digital, internet, logiciels",
           children: [
             { value: "62", label: "Agence de création digitale & SSII" },
             { value: "63", label: "Blogs & sites internet" },
             { value: "64", label: "Plateformes, logiciels et applications" },
             { value: "65", label: "Service IT & E-commerce numérique" },
           ],
         },
         {
           value: "12",
           label: "Édition, médias",
           children: [
             { value: "66", label: "Édition" },
             { value: "67", label: "Médias numériques & papiers" },
           ],
         },
         {
           value: "13",
           label: "Enseignement, formation",
           children: [
             { value: "68", label: "Organismes de formation" },
             { value: "69", label: "Universités & grandes écoles" },
           ],
         },
         {
           value: "14",
           label: "Entretien, maintenance, nettoyage, désinfection",
           children: [
             { value: "70", label: "Fabrication & vente de produits d'entretien" },
             { value: "71", label: "Lutte contre les nuisibles, désinfection, désinsectisation" },
             { value: "72", label: "Service de nettoyage" },
           ],
         },
         {
           value: "15",
           label: "Événementiel",
           children: [
             { value: "73", label: "Agence évènementielle" },
             { value: "74", label: "Évènements professionnels" },
             { value: "75", label: "Évènements sportifs" },
             { value: "76", label: "Festivals" },
             { value: "77", label: "Ingénierie évènementielle" },
             { value: "78", label: "Lieux de réception et de séminaire" },
           ],
         },
         {
           value: "17",
           label: "Imprimerie, emballage, display",
           children: [
             { value: "80", label: "Emballage & conditionnement" },
             { value: "81", label: "Imprimerie & service d'impression" },
             { value: "82", label: "Papeterie & objets imprimés" },
             { value: "83", label: "Solutions & équipements d'exposition, display & agencements" },
           ],
         },
         {
           value: "18",
           label: "Informatique, télécoms",
           children: [
             { value: "84", label: "Hébergement web & cloud" },
             { value: "85", label: "Sécurité numérique" },
             { value: "86", label: "Télécommunications" },
           ],
         },
         {
           value: "19",
           label: "Industrie, ingénierie, R&D",
           children: [
             { value: "87", label: "Bureau d'études en ingénierie" },
             { value: "88", label: "Industrie manufacturière" },
             { value: "89", label: "Matériaux" },
             { value: "90", label: "Matériaux & matières plastiques" },
             { value: "91", label: "Outils, équipement & machinerie industrielle" },
             { value: "92", label: "Signalétiques & équipements urbains" },
           ],
         },
         {
           value: "20",
           label: "Jeux, sports, loisirs",
           children: [
             { value: "93", label: "Activités d'extérieur" },
             { value: "94", label: "Club sportif amateur" },
             { value: "95", label: "Club sportif professionnel" },
             { value: "96", label: "Commerce d'équipements sportifs" },
             { value: "97", label: "Jeux & jouets" },
             { value: "98", label: "Jeux vidéos" },
             { value: "99", label: "Salle de jeux vidéos" },
             { value: "100", label: "Salle de sport & fitness" },
           ],
         },
         {
           value: "21",
           label: "Maison, mobilier, fleuriste, jardin",
           children: [
             { value: "101", label: "Bricolage, quincaillerie" },
             { value: "102", label: "Fleuriste, jardinerie & semences" },
             { value: "103", label: "Literie & linge de maison" },
             { value: "104", label: "Menuiseries & huisseries" },
             { value: "105", label: "Mobilier, décoration, arts de table, vaisselle" },
             { value: "106", label: "Paysagerie & jardinage" },
             { value: "107", label: "Peintures & Laques" },
             { value: "108", label: "Serres & potagers" },
           ],
         },
         {
           value: "22",
           label: "Matériel électrique, électroménager, électronique",
           children: [
             { value: "109", label: "Conception & reconditionnement d'équipements électriques" },
             { value: "110", label: "Réparation de matériel électronique" },
             { value: "111", label: "Vente & location d'équipements électriques et électroniques" },
           ],
         },
         {
           value: "23",
           label: "Mode, textile, accessoires, maroquinerie",
           children: [
             { value: "112", label: "Créateurs d'accessoires de mode" },
             { value: "113", label: "Créateurs de vêtements ou lingerie" },
             { value: "114", label: "Créateurs de chaussures" },
             { value: "115", label: "Créateurs de bijoux (joaillerie, orfèvres)" },
             { value: "116", label: "Créateurs de maroquinerie" },
             { value: "117", label: "Fabrication textile" },
             { value: "118", label: "Fabricants de tissus" },
             { value: "119", label: "Fournisseurs de textile" },
             { value: "120", label: "Fournisseurs de fils et matériaux de couture" },
             { value: "121", label: "Fournisseurs d'équipements pour la fabrication textile" },
             { value: "122", label: "Magasins de prêt-à-porter" },
             { value: "123", label: "Magasins de tissus" },
             { value: "124", label: "Recyclerie textile" },
             { value: "125", label: "Vente de textile" },
             { value: "126", label: "Ateliers de couture (patronage, montage de vêtements, broderie)" },
             { value: "127", label: "Atelier de confection (usines de tricotage, usines de tissage)" },
             { value: "128", label: "Magasins de vêtements" },
             { value: "129", label: "Vente en ligne de vêtements" },
           ],
         },
         {
           value: "24",
           label: "Restauration, traiteur",
           children: [
             { value: "130", label: "Restauration" },
             { value: "131", label: "Restauration collective et d'entreprise" },
             { value: "132", label: "Traiteurs & Foodtruck" },
             { value: "133", label: "Vente de repas en ligne" },
           ],
         },
         {
           value: "25",
           label: "Santé, sécurité, pharmacie",
           children: [
             { value: "134", label: "Dispositifs médicaux et de bien-être" },
             { value: "135", label: "Opticien" },
             { value: "136", label: "Service de santé & sécurité au travail" },
             { value: "137", label: "Vitamines & compléments alimentaires" },
           ],
         },
         {
           value: "26",
           label: "Services aux entreprises",
           children: [
             { value: "138", label: "Agences & plateformes de recrutement" },
             { value: "139", label: "Chasseurs de tête" },
             { value: "140", label: "Chèques cadeaux & titres-restaurant" },
             { value: "141", label: "Incubateurs & accélérateurs" },
             { value: "142", label: "Organisation de séminaires et de voyages en entreprise" },
             { value: "143", label: "Sécurité, gardiennage & conciergerie" },
             { value: "144", label: "Services divers" },
           ],
         },
         {
           value: "27",
           label: "Services aux particuliers",
           children: [
             { value: "145", label: "Coaching & accompagnement personnel" },
             { value: "146", label: "Crèche" },
             { value: "147", label: "Organisateur d'évènements pour particuliers" },
             { value: "148", label: "Photographes & vidéastes" },
           ],
         },
         {
           value: "28",
           label: "Tourisme, hôtellerie",
           children: [
             { value: "149", label: "Camping" },
             { value: "150", label: "Guide touristique" },
             { value: "151", label: "Hôtel, gîte & auberge" },
             { value: "152", label: "Office de tourisme" },
             { value: "153", label: "Réservation de voyages, hébergements & activités touristiques" },
           ],
         },
         {
           value: "29",
           label: "Transports, logistique",
           children: [
             { value: "154", label: "Coursiers & services postaux" },
             { value: "155", label: "Logistique & stockage de marchandises" },
             { value: "156", label: "Plateforme & logiciel de gestion de fret" },
             { value: "157", label: "Plateforme de covoiturage" },
             { value: "158", label: "Taxis, VTC & transport évènementiel" },
             { value: "159", label: "Transport de personnes multimodales" },
           ],
         },
      ],
    },
  },
  {
    formName: "Votre fonction",
    formType: "select",
    name: "fonction",
    content: {
      label: "Quelle est votre fonction au sein de votre entreprise ?",
      placeholder: "Sélectionnez votre fonction",
      options: [
        { value: "Directeur général", label: "Directeur général" },
        { value: "Président", label: "Président" },
        { value: "Salarié", label: "Salarié" },
      ],
    },
  },
]